### ISSUE TITLE
Transition the sticky header

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#160]
@adiraomj Let's look at transitioning the sticky header. Should we fade it in? Any other ideas. At the moment there is a little jump as it goes sticky, many users have raised that recently, the most recent being Greg. Let's chat about this here or on Slack before proceeding. Thanks :)

@AlexGStapleton If you have any transition preferences, perhaps an example or two, let us know.

@gregpriday Same, any preferences or examples you dig, let us know. Thanks guys.

**Comment by AlexGStapleton** [comment]
Okay. So currently (from how it looks) the sentinel doesn't have a height So in theory, to fix this issue we simply need to ensure it's being correctly given the height as that'll prevent the jump - the navigation may have been removed but the spacing is still present due to the sentinel. Thoughts? @adiraomj
