### ISSUE TITLE
Ellipsis is missing from end of post excerpt

### ISSUE THREAD

**Issue by frontenddevguy** [siteorigin/siteorigin-unwind#200]
Ellipsis is missing from end of post excerpt (found in extras.php)

Bug is visible in your demo site.
http://demo.siteorigin.com/unwind/

**Comment by Misplon** [comment]
Hi @frontenddevguy 

Are you using the "Post Excerpt Read More Link. Display the Read More link below the post excerpt." setting? 

I can fix the dots issue quite easily if that setting is disabled. If it's enabled, we'll need to investigate further.

**Comment by Misplon** [comment]
@adiraomj Please, can you see if you're able to get the excerpt read more button working in conjunction with the "..." added to the end of the text when the excerpt is in use. I haven't had any luck. The function we're working with is:

https://github.com/siteorigin/siteorigin-unwind/blob/develop/inc/template-tags.php#L306-L320

**Comment by frontenddevguy** [comment]
Hi, did this ever get fixed?

**Comment by Misplon** [comment]
Hi @frontenddevguy. Thanks for posting. The issue is still open. As soon as the issue is resolved, the fixing commit will be linked here and the issue closed.

You can override the [entire function](https://github.com/siteorigin/siteorigin-unwind/blob/develop/inc/template-tags.php#L306-L320) in question. Add that function to your child theme functions.php file or to a plugin like Code Snippets. Change the function contents to: `return '[.....]';`

**Comment by Misplon** [comment]
We just need to finish a few other tasks, then I'll ask Adi to take a look for us. Let me know if you'd like help with the above hotfix.
