### ISSUE TITLE
Font Settings: Site Title

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-unwind#46]
Consider adding a font-family setting for the site title. Alex keen for us to add a site title color too. I'm concerned about opening the door to too many settings. Keen to add the font-family for the moment. @adiraomj thoughts.

**Comment by adiraomj** [comment]
I feel if we are going to have a font-family field for the site title we might as well have a color field as well. 

Don't think either is necessary though. The headings font should be good enough for now. We could consider adding these fields if we get user requests for them. Otherwise we will be unnecessarily bloating up the settings.

**Comment by Misplon** [comment]
Cool, I'm good with that. Leave for now.
